### PR TITLE
Update TipCalc Droid docs / Bring bullets back

### PR DESCRIPTION
**Pull request by nmilcoff**
Very first step of #3. Still lots of pages to fix.

I couldn't find the images that should appear on the bottom of the document (TipCalc Android UI). It was missing in the readme site too...

The URLs are 
1) https://raw.github.com/slodge/MvvmCross/v3/v3Tutorial/Pictures/TipCalc_Android.png
2) https://raw.github.com/slodge/MvvmCross/v3/v3Tutorial/Pictures/TipCalc_Android_Styled.png

### CODE REVIEW

**Comment by Cheesebaron** [comment]
You can just add the images to your PR?

**Comment by nmilcoff** [comment]
Sure, but the problem is... they don't exist there and I couldn't find them elsewhere

**Comment by Cheesebaron** [comment]
Hmm, no idea where they are, looking through the repositories... 🔍

**Comment by Cheesebaron** [comment]
They are here: https://github.com/MvvmCross/MvvmCross/tree/3.0.13/v3Tutorial/Pictures

**Comment by nmilcoff** [comment]
Awesome, thank you! Have to say they look pretty old though. Should be changed in the future

**Comment by Cheesebaron** [comment]
@nmilcoff yeah, we should tune them to look nice.

**Pull request merged**
